import type { RecommendationResponse } from '../types/recommendation';

export const fallbackRecommendation: RecommendationResponse = {
  farm_analysis: {
    district: 'Lahore',
    season: 'Rabi',
    soil_type: 'Loamy',
    land_area: 10,
    water_availability: 'Medium',
    weather_summary: 'Stable conditions with mild rainfall and moderate humidity.',
  },
  recommended_crops: [
    {
      crop_name: 'Wheat',
      suitability_score: 92,
      confidence_score: 88,
      expected_profit: 125000,
      estimated_yield: 3.8,
      risk_level: 'Low',
      water_requirement: 'Moderate',
      weather_compatibility: 94,
      final_score: 92,
      score_breakdown: {
        soil_score: 95,
        weather_score: 94,
        water_score: 88,
        profit_score: 90,
        risk_score: 95,
        season_score: 100,
        district_multiplier: 1.05,
        final_score: 92,
        weather_contribution: 23.5,
      },
      explanation: 'Wheat is highly suited to your soil and season, with strong market demand and reliable yield estimates.',
      recommendation_reasons: ['High soil compatibility', 'Strong market margin', 'Stable water supply'],
      recommendation_strength: 'Strong',
    },
    {
      crop_name: 'Maize',
      suitability_score: 78,
      confidence_score: 72,
      expected_profit: 82000,
      estimated_yield: 2.7,
      risk_level: 'Medium',
      water_requirement: 'High',
      weather_compatibility: 86,
      final_score: 78,
      score_breakdown: {
        soil_score: 82,
        weather_score: 86,
        water_score: 70,
        profit_score: 78,
        risk_score: 70,
        season_score: 88,
        district_multiplier: 1.0,
        final_score: 78,
        weather_contribution: 21.5,
      },
      explanation: 'Maize remains a valuable secondary crop, especially with additional irrigation support.',
      recommendation_reasons: ['Good profit potential', 'High demand', 'Moderate weather fit'],
      recommendation_strength: 'Moderate',
    },
    {
      crop_name: 'Sesame',
      suitability_score: 64,
      confidence_score: 60,
      expected_profit: 56000,
      estimated_yield: 1.9,
      risk_level: 'High',
      water_requirement: 'Low',
      weather_compatibility: 72,
      final_score: 64,
      score_breakdown: {
        soil_score: 60,
        weather_score: 72,
        water_score: 65,
        profit_score: 60,
        risk_score: 35,
        season_score: 70,
        district_multiplier: 0.95,
        final_score: 64,
        weather_contribution: 18.0,
      },
      explanation: 'Sesame can add diversity with lower water usage, but carries higher weather sensitivity.',
      recommendation_reasons: ['Low irrigation need', 'Niche market', 'Higher weather risk'],
      recommendation_strength: 'Weak',
    },
  ],
  land_allocation: [
    { crop_name: 'Wheat', allocation_percentage: 55, acreage_allocation: 5.5 },
    { crop_name: 'Maize', allocation_percentage: 30, acreage_allocation: 3 },
    { crop_name: 'Sesame', allocation_percentage: 15, acreage_allocation: 1.5 },
  ],
  weather_alerts: [
    { message: 'Light rainfall expected over the next three days.', severity: 'Advisory' },
    { message: 'Monitor humidity as temperatures rise after midday.', severity: 'Watch' },
  ],
  irrigation_advice: {
    advice_text: 'Maintain irrigation every 3 days and avoid overwatering sensitive plots.',
    recommended_actions: ['Check soil moisture', 'Use drip irrigation', 'Delay watering during rain showers'],
  },
  profitability_summary: {
    total_expected_profit: 262000,
    average_profit_per_acre: 26200,
    highest_profit_crop: 'Wheat',
  },
  generated_at: new Date().toISOString(),
  ai_confidence_score: 82,
};
